/*******************************************************************************
 * xFramium
 *
 * Copyright 2016 by Moreland Labs LTD (http://www.morelandlabs.com)
 *
 * Some open source application is free software: you can redistribute 
 * it and/or modify it under the terms of the GNU General Public 
 * License as published by the Free Software Foundation, either 
 * version 3 of the License, or (at your option) any later version.
 *  
 * Some open source application is distributed in the hope that it will 
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with xFramium.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.08 at 09:51:56 AM EST 
//


package com.xframium.page.element.provider.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


// TODO: Auto-generated Javadoc
/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.perfectoMobile.page.element.provider.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /** The Constant _ElementDefinition_QNAME. */
    private final static QName _ElementDefinition_QNAME = new QName("http://www.xframium.org/pageRegistry", "elementDefinition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.perfectoMobile.page.element.provider.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistryRoot }.
     *
     * @return the registry root
     */
    public RegistryRoot createRegistryRoot() {
        return new RegistryRoot();
    }

    /**
     * Create an instance of {@link Import }.
     *
     * @return the import
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Site }.
     *
     * @return the site
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link Page }.
     *
     * @return the page
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link Element }.
     *
     * @return the element
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryRoot }{@code >}}.
     *
     * @param value the value
     * @return the JAXB element< registry root>
     */
    @XmlElementDecl(namespace = "http://www.xframium.org/pageRegistry", name = "elementDefinition")
    public JAXBElement<RegistryRoot> createElementDefinition(RegistryRoot value) {
        return new JAXBElement<RegistryRoot>(_ElementDefinition_QNAME, RegistryRoot.class, null, value);
    }

}
