drop table APPLICATIONS;
drop table APP_DEV_CAPABILITIES;

create table APPLICATIONS
(
        NAME VARCHAR(50) NOT NULL,
        APP_PACKAGE VARCHAR(100),
        BUNDLE_ID VARCHAR(100),
        URL VARCHAR(200),
        IOS_INSTALL VARCHAR(200),
        ANDROID_INSTALL VARCHAR(200)
);

create table APP_DEV_CAPABILITIES
(
        APP_NAME VARCHAR(50) NOT NULL,
        NAME VARCHAR(50) NOT NULL,
        CLASS VARCHAR(50) DEFAULT 'STRING' NOT NULL,
        VALUE VARCHAR(1000) NOT NULL,
        CONSTRAINT CHK_CLASS_2 CHECK (CLASS IN ( 'BOOLEAN', 'OBJECT', 'PLATFORM', 'STRING' ))
);
