var testData = {"pageData": {
    "startTime": {
        "dateTime": "12/22/2016-11:26:03",
        "dateOnly": "12/22/2016",
        "timeOnly": "11:26:03",
        "raw": 1482423963134
    },
    "reportFolder": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\12-22_11-26-07-473",
    "executionSummary": [
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "e8f6d17c-94a8-4aaa-bc82-25d25af38214",
            "cloud": {
                "hostName": "127.0.0.1:4444",
                "proxyPort": "0",
                "password": "",
                "deviceAction": "SELENIUM",
                "provider": "SELENIUM",
                "gridInstance": "null",
                "name": "EMBEDDED",
                "description": "",
                "userName": "",
                "proxyHost": "",
                "gesture": "SELENIUM"
            },
            "total": "5",
            "testStatus": "PASSED",
            "name": "xFramium Step Tags",
            "startTime": {
                "dateTime": "12/22/2016-11:26:07",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:07",
                "raw": 1482423967322
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:07",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:07",
                "raw": 1482423967473
            },
            "passed": "5",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@7579c156[Permits = 1]",
                "deviceName": "Firefox Local",
                "resolution": "1280 x 936",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "EMBEDDED",
                "environment": "Microsoft Corporation Firefox 46 (1280 x 936)",
                "osVersion": "null",
                "browserVersion": "46",
                "availableDevices": "1",
                "browserName": "Firefox",
                "model": "null",
                "cachedString": "null",
                "key": "Firefox Local"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "12d53dc2-5eba-4277-ae78-d53c7925c049",
            "cloud": {
                "hostName": "127.0.0.1:4444",
                "proxyPort": "0",
                "password": "",
                "deviceAction": "SELENIUM",
                "provider": "SELENIUM",
                "gridInstance": "null",
                "name": "EMBEDDED",
                "description": "",
                "userName": "",
                "proxyHost": "",
                "gesture": "SELENIUM"
            },
            "total": "9",
            "testStatus": "PASSED",
            "name": "xFramium REGEX",
            "startTime": {
                "dateTime": "12/22/2016-11:26:12",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:12",
                "raw": 1482423972383
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:12",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:12",
                "raw": 1482423972770
            },
            "passed": "9",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@760edb59[Permits = 1]",
                "deviceName": "Firefox Local",
                "resolution": "1280 x 936",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "EMBEDDED",
                "environment": "Microsoft Corporation Firefox 46 (1280 x 936)",
                "osVersion": "null",
                "browserVersion": "46",
                "availableDevices": "1",
                "browserName": "Firefox",
                "model": "null",
                "cachedString": "null",
                "key": "Firefox Local"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "54728522d394488899df85cff3c1c42c",
            "cloud": {
                "hostName": "ondemand.saucelabs.com:80",
                "proxyPort": "null",
                "password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
                "deviceAction": "null",
                "provider": "SAUCELABS",
                "gridInstance": "EMBEDDED",
                "name": "saucelabs",
                "description": "",
                "userName": "morelandlabs",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "9",
            "testStatus": "PASSED",
            "name": "xFramium REGEX",
            "startTime": {
                "dateTime": "12/22/2016-11:26:10",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:10",
                "raw": 1482423970351
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:15",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:15",
                "raw": 1482423975508
            },
            "passed": "9",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@100e68ee[Permits = 1]",
                "deviceName": "Chrome SauceLabs",
                "resolution": "1032 x 776",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "saucelabs",
                "environment": "Microsoft Corporation Chrome 49 53 (1032 x 776)",
                "osVersion": "null",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "Chrome 49",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome SauceLabs"
            }
        },
        {
            "exceptionType": "CONFIGURATION",
            "ignored": "0",
            "failed": "2",
            "sessionId": "4f8e7235-9d37-4f06-97c5-e270c0252c23",
            "cloud": {
                "hostName": "127.0.0.1:4444",
                "proxyPort": "0",
                "password": "",
                "deviceAction": "SELENIUM",
                "provider": "SELENIUM",
                "gridInstance": "null",
                "name": "EMBEDDED",
                "description": "",
                "userName": "",
                "proxyHost": "",
                "gesture": "SELENIUM"
            },
            "total": "32",
            "testStatus": "FAILED",
            "name": "xFramium General KeyWord Test",
            "startTime": {
                "dateTime": "12/22/2016-11:26:19",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:19",
                "raw": 1482423979549
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:21",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:21",
                "raw": 1482423981041
            },
            "passed": "30",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@169b288f[Permits = 1]",
                "deviceName": "Firefox Local",
                "resolution": "1280 x 936",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "EMBEDDED",
                "environment": "Microsoft Corporation Firefox 46 (1280 x 936)",
                "osVersion": "null",
                "browserVersion": "46",
                "availableDevices": "1",
                "browserName": "Firefox",
                "model": "null",
                "cachedString": "null",
                "key": "Firefox Local"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "356cafbd5ac441cfa7a714784b401ca8",
            "cloud": {
                "hostName": "ondemand.saucelabs.com:80",
                "proxyPort": "null",
                "password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
                "deviceAction": "null",
                "provider": "SAUCELABS",
                "gridInstance": "EMBEDDED",
                "name": "saucelabs",
                "description": "",
                "userName": "morelandlabs",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "4",
            "testStatus": "PASSED",
            "name": "xFramium OS Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:26:23",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:23",
                "raw": 1482423983106
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:24",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:24",
                "raw": 1482423984166
            },
            "passed": "4",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@4791e26e[Permits = 1]",
                "deviceName": "Chrome SauceLabs",
                "resolution": "1032 x 776",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "saucelabs",
                "environment": "Microsoft Corporation Chrome 49 53 (1032 x 776)",
                "osVersion": "null",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "Chrome 49",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome SauceLabs"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "20a6e611-9662-4479-9cfc-29c8c15586c0",
            "cloud": {
                "hostName": "127.0.0.1:4444",
                "proxyPort": "0",
                "password": "",
                "deviceAction": "SELENIUM",
                "provider": "SELENIUM",
                "gridInstance": "null",
                "name": "EMBEDDED",
                "description": "",
                "userName": "",
                "proxyHost": "",
                "gesture": "SELENIUM"
            },
            "total": "4",
            "testStatus": "PASSED",
            "name": "xFramium OS Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:26:25",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:25",
                "raw": 1482423985786
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:25",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:25",
                "raw": 1482423985877
            },
            "passed": "4",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@6da0c3da[Permits = 1]",
                "deviceName": "Firefox Local",
                "resolution": "1280 x 936",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "EMBEDDED",
                "environment": "Microsoft Corporation Firefox 46 (1280 x 936)",
                "osVersion": "null",
                "browserVersion": "46",
                "availableDevices": "1",
                "browserName": "Firefox",
                "model": "null",
                "cachedString": "null",
                "key": "Firefox Local"
            }
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium General KeyWord Test",
            "startTime": {
                "dateTime": "12/22/2016-11:26:28",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:28",
                "raw": 1482423988320
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:28",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:28",
                "raw": 1482423988320
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "SKIPPED",
            "name": "xFramium Page Element Context",
            "startTime": {
                "dateTime": "12/22/2016-11:26:31",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:31",
                "raw": 1482423991850
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:31",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:31",
                "raw": 1482423991850
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "CONFIGURATION",
            "ignored": "0",
            "failed": "3",
            "sessionId": "9a56138ae5fb41739d5c573cdd8bc9af",
            "cloud": {
                "hostName": "ondemand.saucelabs.com:80",
                "proxyPort": "null",
                "password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
                "deviceAction": "null",
                "provider": "SAUCELABS",
                "gridInstance": "EMBEDDED",
                "name": "saucelabs",
                "description": "",
                "userName": "morelandlabs",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "46",
            "testStatus": "FAILED",
            "name": "xFramium General KeyWord Test",
            "startTime": {
                "dateTime": "12/22/2016-11:26:33",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:33",
                "raw": 1482423993885
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:46",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:46",
                "raw": 1482424006883
            },
            "passed": "43",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@f4c5b87[Permits = 1]",
                "deviceName": "Chrome SauceLabs",
                "resolution": "1032 x 776",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "saucelabs",
                "environment": "Microsoft Corporation Chrome 49 53 (1032 x 776)",
                "osVersion": "null",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "Chrome 49",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome SauceLabs"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "SKIPPED",
            "name": "xFramium Page Element Context",
            "startTime": {
                "dateTime": "12/22/2016-11:26:53",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:53",
                "raw": 1482424013788
            },
            "endTime": {
                "dateTime": "12/22/2016-11:26:53",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:53",
                "raw": 1482424013788
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "6d372c5adf5d4c2aa1e96bad0fe1ba2f",
            "cloud": {
                "hostName": "ondemand.saucelabs.com:80",
                "proxyPort": "null",
                "password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
                "deviceAction": "null",
                "provider": "SAUCELABS",
                "gridInstance": "EMBEDDED",
                "name": "saucelabs",
                "description": "",
                "userName": "morelandlabs",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "5",
            "testStatus": "PASSED",
            "name": "xFramium Step Tags",
            "startTime": {
                "dateTime": "12/22/2016-11:27:07",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:07",
                "raw": 1482424027751
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:09",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:09",
                "raw": 1482424029215
            },
            "passed": "5",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@3f966547[Permits = 1]",
                "deviceName": "Chrome SauceLabs",
                "resolution": "1032 x 776",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "saucelabs",
                "environment": "Microsoft Corporation Chrome 49 53 (1032 x 776)",
                "osVersion": "null",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "Chrome 49",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome SauceLabs"
            }
        },
        {
            "exceptionType": "CONFIGURATION",
            "ignored": "0",
            "failed": "3",
            "sessionId": "ageary@morelandlabs.com_RemoteWebDriver_16-12-22_16_26_03_16862",
            "cloud": {
                "hostName": "partners.perfectomobile.com",
                "proxyPort": "null",
                "password": "Spike123!",
                "deviceAction": "null",
                "provider": "PERFECTO",
                "gridInstance": "null",
                "name": "perfecto",
                "description": "",
                "userName": "ageary@morelandlabs.com",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "46",
            "testStatus": "FAILED",
            "name": "xFramium General KeyWord Test",
            "startTime": {
                "dateTime": "12/22/2016-11:26:37",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:26:37",
                "raw": 1482423997125
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:11",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:11",
                "raw": 1482424031546
            },
            "passed": "43",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "Windows",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@2e217836[Permits = 1]",
                "deviceName": "1_DB3D556E-0F3E-466E-9008-D189C0C38248",
                "resolution": "1024x768",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft",
                "cloud": "perfecto",
                "environment": "Microsoft / Windows 8.1 chrome 53 (1024x768)",
                "osVersion": "8.1",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "chrome",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome Perfecto"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "9470d36c2f4c4baebe03ca62a2b18cd1",
            "cloud": {
                "hostName": "ondemand.saucelabs.com:80",
                "proxyPort": "null",
                "password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
                "deviceAction": "null",
                "provider": "SAUCELABS",
                "gridInstance": "EMBEDDED",
                "name": "saucelabs",
                "description": "",
                "userName": "morelandlabs",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "6",
            "testStatus": "PASSED",
            "name": "xFramium Dump State Test",
            "startTime": {
                "dateTime": "12/22/2016-11:27:15",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:15",
                "raw": 1482424035893
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:18",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:18",
                "raw": 1482424038724
            },
            "passed": "6",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@3c6bf528[Permits = 1]",
                "deviceName": "Chrome SauceLabs",
                "resolution": "1032 x 776",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "saucelabs",
                "environment": "Microsoft Corporation Chrome 49 53 (1032 x 776)",
                "osVersion": "null",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "Chrome 49",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome SauceLabs"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "8aaf5334-b051-4442-b199-5b4ca8c83c7a",
            "cloud": {
                "hostName": "127.0.0.1:4444",
                "proxyPort": "0",
                "password": "",
                "deviceAction": "SELENIUM",
                "provider": "SELENIUM",
                "gridInstance": "null",
                "name": "EMBEDDED",
                "description": "",
                "userName": "",
                "proxyHost": "",
                "gesture": "SELENIUM"
            },
            "total": "6",
            "testStatus": "PASSED",
            "name": "xFramium Dump State Test",
            "startTime": {
                "dateTime": "12/22/2016-11:27:24",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:24",
                "raw": 1482424044360
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:24",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:24",
                "raw": 1482424044789
            },
            "passed": "6",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@7f79c39d[Permits = 1]",
                "deviceName": "Firefox Local",
                "resolution": "1280 x 936",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "EMBEDDED",
                "environment": "Microsoft Corporation Firefox 46 (1280 x 936)",
                "osVersion": "null",
                "browserVersion": "46",
                "availableDevices": "1",
                "browserName": "Firefox",
                "model": "null",
                "cachedString": "null",
                "key": "Firefox Local"
            }
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium Dump State Test",
            "startTime": {
                "dateTime": "12/22/2016-11:27:26",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:26",
                "raw": 1482424046259
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:26",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:26",
                "raw": 1482424046259
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "6010de40-2aa3-45fc-9ba4-ec1126740181",
            "cloud": {
                "hostName": "127.0.0.1:4444",
                "proxyPort": "0",
                "password": "",
                "deviceAction": "SELENIUM",
                "provider": "SELENIUM",
                "gridInstance": "null",
                "name": "EMBEDDED",
                "description": "",
                "userName": "",
                "proxyHost": "",
                "gesture": "SELENIUM"
            },
            "total": "6",
            "testStatus": "PASSED",
            "name": "xFramium Dump State Historical Test",
            "startTime": {
                "dateTime": "12/22/2016-11:27:29",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:29",
                "raw": 1482424049995
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:30",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:30",
                "raw": 1482424050462
            },
            "passed": "6",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@5311eb3a[Permits = 1]",
                "deviceName": "Firefox Local",
                "resolution": "1280 x 936",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "EMBEDDED",
                "environment": "Microsoft Corporation Firefox 46 (1280 x 936)",
                "osVersion": "null",
                "browserVersion": "46",
                "availableDevices": "1",
                "browserName": "Firefox",
                "model": "null",
                "cachedString": "null",
                "key": "Firefox Local"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "9aa094384b5240a593866aecd9a4ed5e",
            "cloud": {
                "hostName": "ondemand.saucelabs.com:80",
                "proxyPort": "null",
                "password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
                "deviceAction": "null",
                "provider": "SAUCELABS",
                "gridInstance": "EMBEDDED",
                "name": "saucelabs",
                "description": "",
                "userName": "morelandlabs",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "6",
            "testStatus": "PASSED",
            "name": "xFramium Dump State Historical Test",
            "startTime": {
                "dateTime": "12/22/2016-11:27:36",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:36",
                "raw": 1482424056308
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:39",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:39",
                "raw": 1482424059064
            },
            "passed": "6",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "null",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@6e95283b[Permits = 1]",
                "deviceName": "Chrome SauceLabs",
                "resolution": "1032 x 776",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft Corporation",
                "cloud": "saucelabs",
                "environment": "Microsoft Corporation Chrome 49 53 (1032 x 776)",
                "osVersion": "null",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "Chrome 49",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome SauceLabs"
            }
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "ageary@morelandlabs.com_RemoteWebDriver_16-12-22_16_27_23_16865",
            "cloud": {
                "hostName": "partners.perfectomobile.com",
                "proxyPort": "null",
                "password": "Spike123!",
                "deviceAction": "null",
                "provider": "PERFECTO",
                "gridInstance": "null",
                "name": "perfecto",
                "description": "",
                "userName": "ageary@morelandlabs.com",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "6",
            "testStatus": "PASSED",
            "name": "xFramium Dump State Test",
            "startTime": {
                "dateTime": "12/22/2016-11:27:53",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:53",
                "raw": 1482424073004
            },
            "endTime": {
                "dateTime": "12/22/2016-11:27:58",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:27:58",
                "raw": 1482424078935
            },
            "passed": "6",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "Windows",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@16e41b60[Permits = 1]",
                "deviceName": "1_DB3D556E-0F3E-466E-9008-D189C0C38248",
                "resolution": "1024x768",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft",
                "cloud": "perfecto",
                "environment": "Microsoft / Windows 8.1 chrome 53 (1024x768)",
                "osVersion": "8.1",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "chrome",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome Perfecto"
            }
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium Dump State Historical Test",
            "startTime": {
                "dateTime": "12/22/2016-11:28:11",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:11",
                "raw": 1482424091266
            },
            "endTime": {
                "dateTime": "12/22/2016-11:28:11",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:11",
                "raw": 1482424091266
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "SKIPPED",
            "name": "xFramium device tag Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:28:16",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:16",
                "raw": 1482424096482
            },
            "endTime": {
                "dateTime": "12/22/2016-11:28:16",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:16",
                "raw": 1482424096482
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "SKIPPED",
            "name": "xFramium device tag Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:28:22",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:22",
                "raw": 1482424102452
            },
            "endTime": {
                "dateTime": "12/22/2016-11:28:22",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:22",
                "raw": 1482424102452
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "ageary@morelandlabs.com_RemoteWebDriver_16-12-22_16_28_10_16868",
            "cloud": {
                "hostName": "partners.perfectomobile.com",
                "proxyPort": "null",
                "password": "Spike123!",
                "deviceAction": "null",
                "provider": "PERFECTO",
                "gridInstance": "null",
                "name": "perfecto",
                "description": "",
                "userName": "ageary@morelandlabs.com",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "6",
            "testStatus": "PASSED",
            "name": "xFramium Dump State Historical Test",
            "startTime": {
                "dateTime": "12/22/2016-11:28:27",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:27",
                "raw": 1482424107387
            },
            "endTime": {
                "dateTime": "12/22/2016-11:28:32",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:32",
                "raw": 1482424112151
            },
            "passed": "6",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "Windows",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@47a77bd4[Permits = 1]",
                "deviceName": "1_DB3D556E-0F3E-466E-9008-D189C0C38248",
                "resolution": "1024x768",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft",
                "cloud": "perfecto",
                "environment": "Microsoft / Windows 8.1 chrome 53 (1024x768)",
                "osVersion": "8.1",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "chrome",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome Perfecto"
            }
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium device tag Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:28:46",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:46",
                "raw": 1482424126439
            },
            "endTime": {
                "dateTime": "12/22/2016-11:28:46",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:28:46",
                "raw": 1482424126439
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "SKIPPED",
            "name": "xFramium device tag Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:29:00",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:00",
                "raw": 1482424140432
            },
            "endTime": {
                "dateTime": "12/22/2016-11:29:00",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:00",
                "raw": 1482424140432
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium Page Element Context",
            "startTime": {
                "dateTime": "12/22/2016-11:29:13",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:13",
                "raw": 1482424153883
            },
            "endTime": {
                "dateTime": "12/22/2016-11:29:13",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:13",
                "raw": 1482424153883
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "SKIPPED",
            "name": "xFramium Page Element Context",
            "startTime": {
                "dateTime": "12/22/2016-11:29:29",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:29",
                "raw": 1482424169048
            },
            "endTime": {
                "dateTime": "12/22/2016-11:29:29",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:29",
                "raw": 1482424169048
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium OS Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:29:42",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:42",
                "raw": 1482424182273
            },
            "endTime": {
                "dateTime": "12/22/2016-11:29:42",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:42",
                "raw": 1482424182273
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "ageary@morelandlabs.com_RemoteWebDriver_16-12-22_16_29_40_16877",
            "cloud": {
                "hostName": "partners.perfectomobile.com",
                "proxyPort": "null",
                "password": "Spike123!",
                "deviceAction": "null",
                "provider": "PERFECTO",
                "gridInstance": "null",
                "name": "perfecto",
                "description": "",
                "userName": "ageary@morelandlabs.com",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "4",
            "testStatus": "PASSED",
            "name": "xFramium OS Step Filter",
            "startTime": {
                "dateTime": "12/22/2016-11:29:57",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:29:57",
                "raw": 1482424197946
            },
            "endTime": {
                "dateTime": "12/22/2016-11:30:00",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:00",
                "raw": 1482424200224
            },
            "passed": "4",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "Windows",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@df417e[Permits = 1]",
                "deviceName": "1_DB3D556E-0F3E-466E-9008-D189C0C38248",
                "resolution": "1024x768",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft",
                "cloud": "perfecto",
                "environment": "Microsoft / Windows 8.1 chrome 53 (1024x768)",
                "osVersion": "8.1",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "chrome",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome Perfecto"
            }
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium Step Tags",
            "startTime": {
                "dateTime": "12/22/2016-11:30:13",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:13",
                "raw": 1482424213367
            },
            "endTime": {
                "dateTime": "12/22/2016-11:30:13",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:13",
                "raw": 1482424213367
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "ageary@morelandlabs.com_RemoteWebDriver_16-12-22_16_30_12_16880",
            "cloud": {
                "hostName": "partners.perfectomobile.com",
                "proxyPort": "null",
                "password": "Spike123!",
                "deviceAction": "null",
                "provider": "PERFECTO",
                "gridInstance": "null",
                "name": "perfecto",
                "description": "",
                "userName": "ageary@morelandlabs.com",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "5",
            "testStatus": "PASSED",
            "name": "xFramium Step Tags",
            "startTime": {
                "dateTime": "12/22/2016-11:30:30",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:30",
                "raw": 1482424230377
            },
            "endTime": {
                "dateTime": "12/22/2016-11:30:33",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:33",
                "raw": 1482424233166
            },
            "passed": "5",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "Windows",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@554b1169[Permits = 1]",
                "deviceName": "1_DB3D556E-0F3E-466E-9008-D189C0C38248",
                "resolution": "1024x768",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft",
                "cloud": "perfecto",
                "environment": "Microsoft / Windows 8.1 chrome 53 (1024x768)",
                "osVersion": "8.1",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "chrome",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome Perfecto"
            }
        },
        {
            "exceptionType": "CLOUD",
            "ignored": "0",
            "failed": "0",
            "sessionId": "null",
            "cloud": "null",
            "total": "0",
            "testStatus": "FAILED",
            "name": "xFramium REGEX",
            "startTime": {
                "dateTime": "12/22/2016-11:30:46",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:46",
                "raw": 1482424246570
            },
            "endTime": {
                "dateTime": "12/22/2016-11:30:46",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:30:46",
                "raw": 1482424246570
            },
            "passed": "0",
            "folderName": "null",
            "device": "null"
        },
        {
            "exceptionType": "null",
            "ignored": "0",
            "failed": "0",
            "sessionId": "ageary@morelandlabs.com_RemoteWebDriver_16-12-22_16_30_45_16884",
            "cloud": {
                "hostName": "partners.perfectomobile.com",
                "proxyPort": "null",
                "password": "Spike123!",
                "deviceAction": "null",
                "provider": "PERFECTO",
                "gridInstance": "null",
                "name": "perfecto",
                "description": "",
                "userName": "ageary@morelandlabs.com",
                "proxyHost": "",
                "gesture": "null"
            },
            "total": "9",
            "testStatus": "PASSED",
            "name": "xFramium REGEX",
            "startTime": {
                "dateTime": "12/22/2016-11:31:01",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:31:01",
                "raw": 1482424261979
            },
            "endTime": {
                "dateTime": "12/22/2016-11:31:10",
                "dateOnly": "12/22/2016",
                "timeOnly": "11:31:10",
                "raw": 1482424270193
            },
            "passed": "9",
            "folderName": "null",
            "device": {
                "capabilities": {},
                "os": "Windows",
                "active": false,
                "deviceLock": "java.util.concurrent.Semaphore@11d08e18[Permits = 1]",
                "deviceName": "1_DB3D556E-0F3E-466E-9008-D189C0C38248",
                "resolution": "1024x768",
                "capList": [],
                "driverType": "WEB",
                "tagNames": [],
                "manufacturer": "Microsoft",
                "cloud": "perfecto",
                "environment": "Microsoft / Windows 8.1 chrome 53 (1024x768)",
                "osVersion": "8.1",
                "browserVersion": "53",
                "availableDevices": "1",
                "browserName": "chrome",
                "model": "null",
                "cachedString": "null",
                "key": "Chrome Perfecto"
            }
        }
    ],
    "suiteName": "Google Search Test"
}};