var testData = {"pageData": {
    "exceptionType": "null",
    "aut": "null",
    "executionParameters": {
        "WCAG_REPORT": "xFramium 2nd Device\\Firefox Local\\wcag.html",
        "CONSOLE_LOG": "xFramium 2nd Device\\Firefox Local\\console.txt",
        "WCAG_REPORT_FILE": "wcag.html",
        "CONSOLE_LOG_FILE": "console.txt"
    },
    "test": {
        "deviceTags": "null",
        "timed": false,
        "os": "null",
        "contentKeys": [""],
        "log": "org.apache.commons.logging.impl.Jdk14Logger@5888bb4c",
        "count": "1",
        "active": true,
        "description": "Tests that the specified step is ignored for a specific OS type",
        "threshold": "0",
        "stepList": [
            {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "existsSingle",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleValue",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            {
                "deviceTags": "null",
                "natualLanguage": "Click on the <span class=\"elementName\">%1%s<\/span> element on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script to click on the center of the named element",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Click",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                "stepList": [],
                "kw": "CLICK",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Interaction",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            {
                "deviceTags": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows thte script to add a additional device to the same script to validate device/device actions",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-adddevice",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Add device",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSAddDevice",
                "stepList": [],
                "kw": "ADD_DEVICE",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "Add Device",
                "parameterList": [{
                    "fileName": "null",
                    "usage": "null",
                    "name": "null",
                    "type": "STATIC",
                    "tokenList": [],
                    "value": "Chrome Local"
                }],
                "category": "Utility",
                "orMapping": false,
                "waitTime": "0",
                "device": "null"
            },
            {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "Chrome Local"
            },
            {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "existsSingle",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleValue",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "Chrome Local"
            },
            {
                "deviceTags": "null",
                "natualLanguage": "Click on the <span class=\"elementName\">%1%s<\/span> element on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script to click on the center of the named element",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Click",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                "stepList": [],
                "kw": "CLICK",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Interaction",
                "orMapping": true,
                "waitTime": "0",
                "device": "Chrome Local"
            }
        ],
        "testTags": [""],
        "linkId": "null",
        "dataDriver": "null",
        "name": "xFramium 2nd Device",
        "dataProviders": ["callTest"]
    },
    "sPMap": {
        "__outputFolder": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output",
        "sun.desktop": "windows",
        "awt.toolkit": "sun.awt.windows.WToolkit",
        "file.encoding.pkg": "sun.io",
        "java.specification.version": "1.8",
        "webdriver.chrome.driver": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\chromedriver.exe",
        "sun.cpu.isalist": "amd64",
        "sun.jnu.encoding": "Cp1252",
        "sun.awt.enableExtraMouseButtons": "true",
        "java.class.path": "C:\\Users\\Allen\\git\\xframium-java\\driver\\bin;C:\\Users\\Allen\\.m2\\repository\\commons-logging\\commons-logging\\1.1.1\\commons-logging-1.1.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\testng\\testng\\6.9.10\\testng-6.9.10.jar;C:\\Users\\Allen\\.m2\\repository\\com\\beust\\jcommander\\1.48\\jcommander-1.48.jar;C:\\Users\\Allen\\.m2\\repository\\org\\beanshell\\bsh\\2.0b4\\bsh-2.0b4.jar;C:\\Users\\Allen\\git\\xframium-java\\framework\\target\\classes;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\poi\\poi-ooxml\\3.11\\poi-ooxml-3.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\poi\\poi\\3.11\\poi-3.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\poi\\poi-ooxml-schemas\\3.11\\poi-ooxml-schemas-3.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\xmlbeans\\xmlbeans\\2.6.0\\xmlbeans-2.6.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-java\\3.0.1\\selenium-java-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-chrome-driver\\3.0.1\\selenium-chrome-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-remote-driver\\3.0.1\\selenium-remote-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\commons\\commons-exec\\1.3\\commons-exec-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\net\\java\\dev\\jna\\jna-platform\\4.1.0\\jna-platform-4.1.0.jar;C:\\Users\\Allen\\.m2\\repository\\net\\java\\dev\\jna\\jna\\4.1.0\\jna-4.1.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-edge-driver\\3.0.1\\selenium-edge-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-firefox-driver\\3.0.1\\selenium-firefox-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-ie-driver\\3.0.1\\selenium-ie-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-opera-driver\\3.0.1\\selenium-opera-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-safari-driver\\3.0.1\\selenium-safari-driver-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\io\\netty\\netty\\3.5.7.Final\\netty-3.5.7.Final.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-support\\3.0.1\\selenium-support-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\junit\\junit\\4.12\\junit-4.12.jar;C:\\Users\\Allen\\.m2\\repository\\org\\hamcrest\\hamcrest-core\\1.3\\hamcrest-core-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit\\2.23\\htmlunit-2.23.jar;C:\\Users\\Allen\\.m2\\repository\\xalan\\xalan\\2.7.2\\xalan-2.7.2.jar;C:\\Users\\Allen\\.m2\\repository\\xalan\\serializer\\2.7.2\\serializer-2.7.2.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\httpcomponents\\httpmime\\4.5.2\\httpmime-4.5.2.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit-core-js\\2.23\\htmlunit-core-js-2.23.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlunit\\neko-htmlunit\\2.23\\neko-htmlunit-2.23.jar;C:\\Users\\Allen\\.m2\\repository\\xerces\\xercesImpl\\2.11.0\\xercesImpl-2.11.0.jar;C:\\Users\\Allen\\.m2\\repository\\xml-apis\\xml-apis\\1.4.01\\xml-apis-1.4.01.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\cssparser\\cssparser\\0.9.20\\cssparser-0.9.20.jar;C:\\Users\\Allen\\.m2\\repository\\org\\w3c\\css\\sac\\1.3\\sac-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\com\\codeborne\\phantomjsdriver\\1.3.0\\phantomjsdriver-1.3.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-client\\9.2.15.v20160210\\websocket-client-9.2.15.v20160210.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\jetty-util\\9.2.15.v20160210\\jetty-util-9.2.15.v20160210.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\jetty-io\\9.2.15.v20160210\\jetty-io-9.2.15.v20160210.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-common\\9.2.15.v20160210\\websocket-common-9.2.15.v20160210.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-api\\9.2.15.v20160210\\websocket-api-9.2.15.v20160210.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-api\\3.0.1\\selenium-api-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-server\\3.0.1\\selenium-server-3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\net\\jcip\\jcip-annotations\\1.0\\jcip-annotations-1.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\jetty-repacked\\9.2.13.v20160825\\jetty-repacked-9.2.13.v20160825.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\servlet\\javax.servlet-api\\3.1.0\\javax.servlet-api-3.1.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\htmlunit-driver\\2.23\\htmlunit-driver-2.23.jar;C:\\Users\\Allen\\.m2\\repository\\org\\yaml\\snakeyaml\\1.15\\snakeyaml-1.15.jar;C:\\Users\\Allen\\.m2\\repository\\io\\appium\\java-client\\4.1.2\\java-client-4.1.2.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\code\\gson\\gson\\2.7\\gson-2.7.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\httpcomponents\\httpclient\\4.5.2\\httpclient-4.5.2.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\httpcomponents\\httpcore\\4.4.4\\httpcore-4.4.4.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\guava\\guava\\19.0\\guava-19.0.jar;C:\\Users\\Allen\\.m2\\repository\\commons-validator\\commons-validator\\1.5.1\\commons-validator-1.5.1.jar;C:\\Users\\Allen\\.m2\\repository\\commons-beanutils\\commons-beanutils\\1.9.2\\commons-beanutils-1.9.2.jar;C:\\Users\\Allen\\.m2\\repository\\commons-digester\\commons-digester\\1.8.1\\commons-digester-1.8.1.jar;C:\\Users\\Allen\\.m2\\repository\\commons-collections\\commons-collections\\3.2.2\\commons-collections-3.2.2.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.4\\commons-lang3-3.4.jar;C:\\Users\\Allen\\.m2\\repository\\cglib\\cglib-nodep\\3.2.4\\cglib-nodep-3.2.4.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-context\\4.3.2.RELEASE\\spring-context-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-aop\\4.3.2.RELEASE\\spring-aop-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-beans\\4.3.2.RELEASE\\spring-beans-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-core\\4.3.2.RELEASE\\spring-core-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-expression\\4.3.2.RELEASE\\spring-expression-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\aspectj\\aspectjweaver\\1.8.9\\aspectjweaver-1.8.9.jar;C:\\Users\\Allen\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-runtime\\2.2.11\\jaxb-runtime-2.2.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-core\\2.2.11\\jaxb-core-2.2.11.jar;C:\\Users\\Allen\\.m2\\repository\\com\\sun\\istack\\istack-commons-runtime\\2.2\\istack-commons-runtime-2.2.jar;C:\\Users\\Allen\\.m2\\repository\\stax\\stax-api\\1.0.1\\stax-api-1.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\activation\\activation\\1.1\\activation-1.1.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlcleaner\\htmlcleaner\\2.17\\htmlcleaner-2.17.jar;C:\\Users\\Allen\\.m2\\repository\\org\\jdom\\jdom2\\2.0.5\\jdom2-2.0.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\antlr4\\4.5\\antlr4-4.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\antlr4-runtime\\4.5\\antlr4-runtime-4.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\abego\\treelayout\\org.abego.treelayout.core\\1.0.1\\org.abego.treelayout.core-1.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\antlr-runtime\\3.5.2\\antlr-runtime-3.5.2.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\ST4\\4.0.8\\ST4-4.0.8.jar;C:\\Users\\Allen\\.m2\\repository\\eu\\bitwalker\\UserAgentUtils\\1.20\\UserAgentUtils-1.20.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\apis\\google-api-services-analyticsreporting\\v4-rev8-1.22.0\\google-api-services-analyticsreporting-v4-rev8-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\api-client\\google-api-client\\1.22.0\\google-api-client-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\oauth-client\\google-oauth-client\\1.22.0\\google-oauth-client-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\http-client\\google-http-client\\1.22.0\\google-http-client-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\code\\findbugs\\jsr305\\1.3.9\\jsr305-1.3.9.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\http-client\\google-http-client-jackson2\\1.22.0\\google-http-client-jackson2-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\fasterxml\\jackson\\core\\jackson-core\\2.1.3\\jackson-core-2.1.3.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\guava\\guava-jdk5\\17.0\\guava-jdk5-17.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\jayway\\jsonpath\\json-path\\2.0.0\\json-path-2.0.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\slf4j\\slf4j-api\\1.7.10\\slf4j-api-1.7.10.jar;C:\\Users\\Allen\\.m2\\repository\\net\\minidev\\json-smart\\2.1.1\\json-smart-2.1.1.jar;C:\\Users\\Allen\\.m2\\repository\\net\\minidev\\asm\\1.0.2\\asm-1.0.2.jar;C:\\Users\\Allen\\.m2\\repository\\asm\\asm\\3.3.1\\asm-3.3.1.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfectomobile\\intellij-connector\\9.2.0.0\\intellij-connector-9.2.0.0.jar;C:\\Users\\Allen\\.m2\\repository\\commons-io\\commons-io\\1.4\\commons-io-1.4.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-testng\\1.1.4\\reportium-testng-1.1.4.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-java\\1.1.4\\reportium-java-1.1.4.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfectomobile\\pm-webdriver\\9.2.0.1\\pm-webdriver-9.2.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfectomobile\\http-client\\9.2.0.1\\http-client-9.2.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\info\\cukes\\gherkin\\2.12.2\\gherkin-2.12.2.jar;C:\\Projects\\Git\\morelandLabs\\xframium-serialization\\target\\classes;C:\\Users\\Allen\\.m2\\repository\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;C:\\Users\\Allen\\.m2\\repository\\org\\json\\json\\20160212\\json-20160212.jar;C:\\Users\\Allen\\.m2\\repository\\com\\experitest\\mobile-webdriver\\9.0\\mobile-webdriver-9.0.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\mail\\mail\\1.5.0-b01\\mail-1.5.0-b01.jar",
        "java.vm.vendor": "Oracle Corporation",
        "sun.arch.data.model": "64",
        "user.variant": "",
        "java.vendor.url": "http://java.oracle.com/",
        "user.timezone": "America/New_York",
        "__userName": "morelandlabs",
        "os.name": "Windows 10",
        "java.vm.specification.version": "1.8",
        "user.country": "US",
        "sun.java.launcher": "SUN_STANDARD",
        "sun.boot.library.path": "C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\bin",
        "sun.java.command": "org.xframium.console.http.ExecutionConsole",
        "sun.cpu.endian": "little",
        "user.home": "C:\\Users\\Allen",
        "user.language": "en",
        "java.specification.vendor": "Oracle Corporation",
        "java.home": "C:\\Program Files\\Java\\jdk1.8.0_71\\jre",
        "file.separator": "\\",
        "line.separator": "\r\n",
        "java.vm.specification.vendor": "Oracle Corporation",
        "java.specification.name": "Java Platform API Specification",
        "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
        "__cloudUrl": "https://ondemand.saucelabs.com:80",
        "sun.boot.class.path": "C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\resources.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\rt.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\jsse.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\jce.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\charsets.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\jfr.jar;C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\classes",
        "user.script": "",
        "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
        "java.runtime.version": "1.8.0_71-b15",
        "user.name": "Allen",
        "path.separator": ";",
        "os.version": "10.0",
        "java.endorsed.dirs": "C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\endorsed",
        "java.runtime.name": "Java(TM) SE Runtime Environment",
        "file.encoding": "Cp1252",
        "__password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
        "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
        "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
        "java.io.tmpdir": "C:\\Users\\Allen\\AppData\\Local\\Temp\\",
        "java.version": "1.8.0_71",
        "user.dir": "C:\\Users\\Allen\\git\\xframium-java\\driver",
        "os.arch": "amd64",
        "webdriver.gecko.driver": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\geckodriver.exe",
        "java.vm.specification.name": "Java Virtual Machine Specification",
        "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
        "sun.os.patch.level": "",
        "java.library.path": "C:\\Program Files\\Java\\jdk1.8.0_71\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:/Program Files/Java/jre1.8.0_111/bin/server;C:/Program Files/Java/jre1.8.0_111/bin;C:/Program Files/Java/jre1.8.0_111/lib/amd64;C:\\oraclexe\\app\\oracle\\product\\11.2.0\\server\\bin;;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Symantec\\VIP Access Client\\;c:\\program files\\java\\jdk1.8.0_71\\bin;C:\\Users\\Allen\\AppData\\Roaming\\npm;C:\\Users\\Allen\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Projects\\Tools\\eclipse;;.",
        "java.vm.info": "mixed mode",
        "java.vendor": "Oracle Corporation",
        "java.vm.version": "25.71-b15",
        "java.ext.dirs": "C:\\Program Files\\Java\\jdk1.8.0_71\\jre\\lib\\ext;C:\\WINDOWS\\Sun\\Java\\lib\\ext",
        "sun.io.unicode.encoding": "UnicodeLittle",
        "java.class.version": "52.0"
    },
    "testException": "null",
    "stepList": [
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278257
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278319
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "existsSingle",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleValue",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278319
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278403
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "Click on the <span class=\"elementName\">%1%s<\/span> element on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script to click on the center of the named element",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Click",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                "stepList": [],
                "kw": "CLICK",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Interaction",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278403
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278452
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": ["Chrome Local"],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows thte script to add a additional device to the same script to validate device/device actions",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-adddevice",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Add device",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSAddDevice",
                "stepList": [],
                "kw": "ADD_DEVICE",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "Add Device",
                "parameterList": [{
                    "fileName": "null",
                    "usage": "null",
                    "name": "null",
                    "type": "STATIC",
                    "tokenList": [],
                    "value": "Chrome Local"
                }],
                "category": "Utility",
                "orMapping": false,
                "waitTime": "0",
                "device": "null"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:38",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:38",
                "raw": 1483362278452
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282479
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "Chrome Local"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282479
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282601
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "Verify that the <span class=\"elementName\">%1%s<\/span> element is present on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script validate that the named element is present in the tree",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-exists",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "existsSingle",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Present",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSExists",
                "stepList": [],
                "kw": "EXISTS",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleValue",
                "parameterList": [],
                "category": "Verification",
                "orMapping": true,
                "waitTime": "0",
                "device": "Chrome Local"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282601
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282756
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "Click on the <span class=\"elementName\">%1%s<\/span> element on the page <span class=\"pageName\">%2%s<\/span>",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@3d99cf02",
                "kwDescription": "Allows the script to click on the center of the named element",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-click",
                "siteName": "null",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Click",
                "numberGenerator": "java.util.Random@2056529f",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSClick",
                "stepList": [],
                "kw": "CLICK",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "toggleButton",
                "parameterList": [],
                "category": "Interaction",
                "orMapping": true,
                "waitTime": "0",
                "device": "Chrome Local"
            },
            "startTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282756
            },
            "endTime": {
                "dateTime": "01/02/2017-08:04:42",
                "dateOnly": "01/02/2017",
                "timeOnly": "08:04:42",
                "raw": 1483362282875
            },
            "stepList": [],
            "message": "null",
            "stepStatus": "SUCCESS"
        }
    ],
    "sessionId": "9e347647-409d-4f9d-af8e-1343088c3cbf",
    "message": "null",
    "moduleMap": {},
    "callMap": {},
    "currentStep": "null",
    "testStatus": "PASSED",
    "dataMap": {"callTest": {
        "recordMap": {"value": "one"},
        "recordName": "one",
        "typeName": "callTest",
        "active": true,
        "containsChildren": false
    }},
    "pageMap": {"xTest.home": {
        "m0": "public native int java.lang.Object.hashCode()",
        "m1": "public boolean java.lang.Object.equals(java.lang.Object)",
        "m2": "public java.lang.String java.lang.Object.toString()",
        "m3": "public abstract java.lang.String org.xframium.page.keyWord.KeyWordPage.getPageName()",
        "m4": "public abstract void org.xframium.page.keyWord.KeyWordPage.setPageName(java.lang.String)",
        "m5": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(org.xframium.page.ElementDescriptor)",
        "m6": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String,java.lang.String)",
        "m7": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String)",
        "m8": "public abstract void org.xframium.page.Page.initializePage()",
        "m9": "public abstract void org.xframium.page.Page.setDriver(java.lang.Object)"
    }},
    "startTime": {
        "dateTime": "01/02/2017-08:04:38",
        "dateOnly": "01/02/2017",
        "timeOnly": "08:04:38",
        "raw": 1483362278254
    },
    "endTime": {
        "dateTime": "01/02/2017-08:04:42",
        "dateOnly": "01/02/2017",
        "timeOnly": "08:04:42",
        "raw": 1483362282875
    },
    "folderName": "xFramium 2nd Device\\Firefox Local\\",
    "cloudDescriptor": {
        "hostName": "127.0.0.1:4444",
        "proxyPort": "0",
        "password": "",
        "deviceAction": "SELENIUM",
        "provider": {
            "name": "SELENIUM",
            "description": "Browsers hosted in a Selenium Grid",
            "id": "1"
        },
        "gridInstance": "null",
        "name": "EMBEDDED",
        "description": "",
        "userName": "",
        "proxyHost": "",
        "gesture": "SELENIUM"
    },
    "contextMap": {"existsSingle": "1"},
    "device": {
        "capabilities": {},
        "os": "WINDOWS",
        "active": false,
        "deviceLock": "java.util.concurrent.Semaphore@231d44c[Permits = 1]",
        "deviceName": "Firefox Local",
        "resolution": "1280 x 936",
        "capList": [],
        "driverType": "WEB",
        "tagNames": [],
        "manufacturer": "Microsoft Corporation",
        "cloud": "EMBEDDED",
        "environment": " Firefox 46",
        "osVersion": "null",
        "browserVersion": "46",
        "availableDevices": "1",
        "browserName": "Firefox",
        "model": "null",
        "cachedString": "null",
        "key": "Firefox Local"
    },
    "testName": "xFramium 2nd Device"
}};