var testData = {"pageData": {
    "exceptionType": "null",
    "aut": "null",
    "timerStart": "0",
    "elementUsageMap": {},
    "elementUsage": [],
    "csvOutput": "",
    "testStatus": "PASSED",
    "dataMap": {},
    "pageMap": {"xTest.home": {
        "m0": "public native int java.lang.Object.hashCode()",
        "m1": "public boolean java.lang.Object.equals(java.lang.Object)",
        "m2": "public java.lang.String java.lang.Object.toString()",
        "m3": "public abstract java.lang.String org.xframium.page.keyWord.KeyWordPage.getPageName()",
        "m4": "public abstract void org.xframium.page.keyWord.KeyWordPage.setPageName(java.lang.String)",
        "m5": "public abstract void org.xframium.page.Page.setExecutionContext(org.xframium.reporting.ExecutionContextTest)",
        "m6": "public abstract org.xframium.reporting.ExecutionContextTest org.xframium.page.Page.getExecutionContext()",
        "m7": "public abstract void org.xframium.page.Page.setDriver(java.lang.Object)",
        "m8": "public abstract void org.xframium.page.Page.initializePage()",
        "m9": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(org.xframium.page.ElementDescriptor)",
        "m11": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String)",
        "m10": "public abstract org.xframium.page.element.Element org.xframium.page.Page.getElement(java.lang.String,java.lang.String)"
    }},
    "pageUsageMap": {},
    "timerName": "null",
    "startTime": {
        "dateTime": "05/26/2017-11:09:54",
        "dateOnly": "05/26/2017",
        "timeOnly": "11:09:54",
        "raw": 1495811394478
    },
    "testName": "SET Test",
    "dC": "Capabilities [{reportPdfUrl=https://allstate.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165&_timestamp[0]=1495811380334, deviceName=97E13ECDB896B4FC689B8AE21D5F97E3E44A5955, platform=ANY, password=, host=allstate.perfectomobile.com, singleTestReportUrl=https://allstate.reporting.perfectomobile.com?externalId[0]=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165&_timestamp[0]=1495811380334, browserName=, takesScreenshot=true, model=iPhone.*, javascriptEnabled=true, platformName=iOS, rotatable=true, testGridReportUrl=https://allstate.reporting.perfectomobile.com?externalId[0]=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165&_timestamp[0]=1495811380334, entityType=remote_web_driver, version=, serverConnector=, securityToken=, executionId=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165, webdriver.remote.sessionid=0ce68887-1f36-4772-bf0e-99a9cad85d7f, locationContextEnabled=true, scriptName=RemoteWebDriver, reportKey=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165, windTunnelReportUrl=https://allstate.reporting.perfectomobile.com?externalId[0]=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165&_timestamp[0]=1495811380334, user=, cssSelectorsEnabled=true}]",
    "executionParameters": {
        "REPORTIUM_ARTIFACT_URL": "https://allstate.reporting.perfectomobile.com?externalId[0]=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165&_timestamp[0]=1495811380334",
        "REPORTIUM": "enabled",
        "TIMING_HTML_PATH": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\iPhone iOS\\SET Test\\timing.html",
        "IMAGING_ANALYSIS_PATH": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\iPhone iOS\\SET Test\\imaging.html",
        "TIMING_HTML_FILE": "timing.html",
        "IMAGING_ANALYSIS_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\iPhone iOS\\SET Test\\imaging.html",
        "CONSOLE_LOG": "enabled",
        "IMAGING_ANALYSIS": "enabled",
        "CONSOLE_LOG_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\iPhone iOS\\SET Test\\console.txt",
        "CONSOLE_LOG_PATH": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\iPhone iOS\\SET Test\\console.txt",
        "TIMING_HTML": "enabled",
        "PERFECTO_WT": "https://allstate.reporting.perfectomobile.com?externalId[0]=alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165&_timestamp[0]=1495811380334",
        "TIMING_HTML_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\iPhone iOS\\SET Test\\timing.html",
        "IMAGING_ANALYSIS_FILE": "imaging.html",
        "CONSOLE_LOG_FILE": "console.txt"
    },
    "c": "Capabilities [{password=Perfecto123, platformVersion=null, browserName=, model=iPhone.*, platformName=iOS, version=, user=alleng@perfectomobile.com, platform=ANY}]",
    "test": {
        "deviceTags": "null",
        "outputPage": "null",
        "severity": "1",
        "timed": false,
        "os": "null",
        "contentKeys": [""],
        "log": "org.apache.commons.logging.impl.Jdk14Logger@500ef6ef",
        "inputPage": "null",
        "count": "0",
        "active": true,
        "description": "SET Test",
        "threshold": "0",
        "expectedParameters": [],
        "stepList": [{
            "deviceTags": "null",
            "natualLanguage": "null",
            "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
            "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
            "validationType": "null",
            "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
            "siteName": "xTest",
            "description": "",
            "threshold": "0",
            "poi": "null",
            "sFailure": "ERROR",
            "pageName": "home",
            "tagNames": "null",
            "numberFormat": "java.text.DecimalFormat@674dc",
            "browser": "null",
            "context": "null",
            "tokenList": [],
            "startAt": false,
            "validation": "null",
            "kwName": "Call Test/Function",
            "numberGenerator": "java.util.Random@2257437",
            "inverse": false,
            "timed": false,
            "os": "null",
            "active": true,
            "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
            "stepList": [],
            "kw": "CALL2",
            "version": "null",
            "breakpoint": false,
            "fork": false,
            "linkId": "null",
            "name": "kw-set",
            "parameterList": [],
            "category": "Flow Control",
            "orMapping": false,
            "waitTime": "0",
            "device": "null"
        }],
        "priority": "1",
        "testTags": ["Keyword"],
        "mode": "null",
        "operationList": "null",
        "linkId": "null",
        "dataDriver": "null",
        "name": "SET Test",
        "dataProviders": "null"
    },
    "sPMap": {
        "__outputFolder": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output",
        "sun.desktop": "windows",
        "awt.toolkit": "sun.awt.windows.WToolkit",
        "file.encoding.pkg": "sun.io",
        "java.specification.version": "1.8",
        "webdriver.chrome.driver": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\chromedriver-1.0.11.exe",
        "sun.cpu.isalist": "amd64",
        "sun.jnu.encoding": "Cp1252",
        "java.class.path": "C:\\Users\\Allen\\git\\xframium-java\\driver\\bin;C:\\Users\\Allen\\.m2\\repository\\commons-logging\\commons-logging\\1.1.1\\commons-logging-1.1.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\testng\\testng\\6.9.10\\testng-6.9.10.jar;C:\\Users\\Allen\\.m2\\repository\\com\\beust\\jcommander\\1.48\\jcommander-1.48.jar;C:\\Users\\Allen\\.m2\\repository\\org\\beanshell\\bsh\\2.0b4\\bsh-2.0b4.jar;C:\\Users\\Allen\\git\\xframium-java\\framework\\target\\classes;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\poi\\poi-ooxml\\3.11\\poi-ooxml-3.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\poi\\poi\\3.11\\poi-3.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\poi\\poi-ooxml-schemas\\3.11\\poi-ooxml-schemas-3.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\xmlbeans\\xmlbeans\\2.6.0\\xmlbeans-2.6.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-java\\3.4.0\\selenium-java-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-chrome-driver\\3.4.0\\selenium-chrome-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-edge-driver\\3.4.0\\selenium-edge-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-firefox-driver\\3.4.0\\selenium-firefox-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-ie-driver\\3.4.0\\selenium-ie-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-opera-driver\\3.4.0\\selenium-opera-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-remote-driver\\3.4.0\\selenium-remote-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-safari-driver\\3.4.0\\selenium-safari-driver-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-support\\3.4.0\\selenium-support-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\cglib\\cglib-nodep\\3.2.4\\cglib-nodep-3.2.4.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\commons\\commons-exec\\1.3\\commons-exec-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;C:\\Users\\Allen\\.m2\\repository\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;C:\\Users\\Allen\\.m2\\repository\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\w3c\\css\\sac\\1.3\\sac-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\cssparser\\cssparser\\0.9.22\\cssparser-0.9.22.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\hamcrest\\hamcrest-core\\1.3\\hamcrest-core-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit\\2.26\\htmlunit-2.26.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlunit\\htmlunit-core-js\\2.26\\htmlunit-core-js-2.26.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlunit\\neko-htmlunit\\2.25\\neko-htmlunit-2.25.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\httpcomponents\\httpclient\\4.5.3\\httpclient-4.5.3.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\httpcomponents\\httpcore\\4.4.6\\httpcore-4.4.6.jar;C:\\Users\\Allen\\.m2\\repository\\org\\apache\\httpcomponents\\httpmime\\4.5.3\\httpmime-4.5.3.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\jetty-io\\9.4.1.v20170120\\jetty-io-9.4.1.v20170120.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\jetty-util\\9.4.1.v20170120\\jetty-util-9.4.1.v20170120.jar;C:\\Users\\Allen\\.m2\\repository\\net\\java\\dev\\jna\\jna\\4.1.0\\jna-4.1.0.jar;C:\\Users\\Allen\\.m2\\repository\\net\\java\\dev\\jna\\jna-platform\\4.1.0\\jna-platform-4.1.0.jar;C:\\Users\\Allen\\.m2\\repository\\junit\\junit\\4.12\\junit-4.12.jar;C:\\Users\\Allen\\.m2\\repository\\com\\codeborne\\phantomjsdriver\\1.4.0\\phantomjsdriver-1.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\htmlunit-driver\\2.26\\htmlunit-driver-2.26.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\servlet\\javax.servlet-api\\3.1.0\\javax.servlet-api-3.1.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-api\\9.4.3.v20170317\\websocket-api-9.4.3.v20170317.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-client\\9.4.3.v20170317\\websocket-client-9.4.3.v20170317.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\jetty-client\\9.4.3.v20170317\\jetty-client-9.4.3.v20170317.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\jetty-http\\9.4.3.v20170317\\jetty-http-9.4.3.v20170317.jar;C:\\Users\\Allen\\.m2\\repository\\org\\eclipse\\jetty\\websocket\\websocket-common\\9.4.3.v20170317\\websocket-common-9.4.3.v20170317.jar;C:\\Users\\Allen\\.m2\\repository\\xalan\\serializer\\2.7.2\\serializer-2.7.2.jar;C:\\Users\\Allen\\.m2\\repository\\xalan\\xalan\\2.7.2\\xalan-2.7.2.jar;C:\\Users\\Allen\\.m2\\repository\\xerces\\xercesImpl\\2.11.0\\xercesImpl-2.11.0.jar;C:\\Users\\Allen\\.m2\\repository\\xml-apis\\xml-apis\\1.4.01\\xml-apis-1.4.01.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-api\\3.4.0\\selenium-api-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\selenium-server\\3.4.0\\selenium-server-3.4.0.jar;C:\\Users\\Allen\\.m2\\repository\\net\\jcip\\jcip-annotations\\1.0\\jcip-annotations-1.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\seleniumhq\\selenium\\jetty-repacked\\9.4.1.v20170120\\jetty-repacked-9.4.1.v20170120.jar;C:\\Users\\Allen\\.m2\\repository\\org\\yaml\\snakeyaml\\1.15\\snakeyaml-1.15.jar;C:\\Users\\Allen\\.m2\\repository\\io\\appium\\java-client\\4.1.2\\java-client-4.1.2.jar;C:\\Users\\Allen\\.m2\\repository\\commons-validator\\commons-validator\\1.5.1\\commons-validator-1.5.1.jar;C:\\Users\\Allen\\.m2\\repository\\commons-beanutils\\commons-beanutils\\1.9.2\\commons-beanutils-1.9.2.jar;C:\\Users\\Allen\\.m2\\repository\\commons-digester\\commons-digester\\1.8.1\\commons-digester-1.8.1.jar;C:\\Users\\Allen\\.m2\\repository\\commons-collections\\commons-collections\\3.2.2\\commons-collections-3.2.2.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-context\\4.3.2.RELEASE\\spring-context-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-aop\\4.3.2.RELEASE\\spring-aop-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-beans\\4.3.2.RELEASE\\spring-beans-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-core\\4.3.2.RELEASE\\spring-core-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\springframework\\spring-expression\\4.3.2.RELEASE\\spring-expression-4.3.2.RELEASE.jar;C:\\Users\\Allen\\.m2\\repository\\org\\aspectj\\aspectjweaver\\1.8.9\\aspectjweaver-1.8.9.jar;C:\\Users\\Allen\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-runtime\\2.2.11\\jaxb-runtime-2.2.11.jar;C:\\Users\\Allen\\.m2\\repository\\org\\jvnet\\staxex\\stax-ex\\1.7.7\\stax-ex-1.7.7.jar;C:\\Users\\Allen\\.m2\\repository\\com\\sun\\xml\\fastinfoset\\FastInfoset\\1.2.13\\FastInfoset-1.2.13.jar;C:\\Users\\Allen\\.m2\\repository\\org\\glassfish\\jaxb\\jaxb-core\\2.2.11\\jaxb-core-2.2.11.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\xml\\bind\\jaxb-api\\2.2.12-b140109.1041\\jaxb-api-2.2.12-b140109.1041.jar;C:\\Users\\Allen\\.m2\\repository\\org\\glassfish\\jaxb\\txw2\\2.2.11\\txw2-2.2.11.jar;C:\\Users\\Allen\\.m2\\repository\\com\\sun\\istack\\istack-commons-runtime\\2.2\\istack-commons-runtime-2.2.jar;C:\\Users\\Allen\\.m2\\repository\\stax\\stax-api\\1.0.1\\stax-api-1.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\activation\\activation\\1.1\\activation-1.1.jar;C:\\Users\\Allen\\.m2\\repository\\net\\sourceforge\\htmlcleaner\\htmlcleaner\\2.17\\htmlcleaner-2.17.jar;C:\\Users\\Allen\\.m2\\repository\\org\\jdom\\jdom2\\2.0.5\\jdom2-2.0.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\antlr4\\4.5\\antlr4-4.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\antlr4-runtime\\4.5\\antlr4-runtime-4.5.jar;C:\\Users\\Allen\\.m2\\repository\\org\\abego\\treelayout\\org.abego.treelayout.core\\1.0.1\\org.abego.treelayout.core-1.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\antlr-runtime\\3.5.2\\antlr-runtime-3.5.2.jar;C:\\Users\\Allen\\.m2\\repository\\org\\antlr\\ST4\\4.0.8\\ST4-4.0.8.jar;C:\\Users\\Allen\\.m2\\repository\\eu\\bitwalker\\UserAgentUtils\\1.20\\UserAgentUtils-1.20.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\apis\\google-api-services-analyticsreporting\\v4-rev111-1.22.0\\google-api-services-analyticsreporting-v4-rev111-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\api-client\\google-api-client\\1.22.0\\google-api-client-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\oauth-client\\google-oauth-client\\1.22.0\\google-oauth-client-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\http-client\\google-http-client\\1.22.0\\google-http-client-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\code\\findbugs\\jsr305\\1.3.9\\jsr305-1.3.9.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\http-client\\google-http-client-jackson2\\1.22.0\\google-http-client-jackson2-1.22.0.jar;C:\\Users\\Allen\\.m2\\repository\\com\\fasterxml\\jackson\\core\\jackson-core\\2.1.3\\jackson-core-2.1.3.jar;C:\\Users\\Allen\\.m2\\repository\\com\\jayway\\jsonpath\\json-path\\2.0.0\\json-path-2.0.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\slf4j\\slf4j-api\\1.7.10\\slf4j-api-1.7.10.jar;C:\\Users\\Allen\\.m2\\repository\\net\\minidev\\json-smart\\2.1.1\\json-smart-2.1.1.jar;C:\\Users\\Allen\\.m2\\repository\\net\\minidev\\asm\\1.0.2\\asm-1.0.2.jar;C:\\Users\\Allen\\.m2\\repository\\asm\\asm\\3.3.1\\asm-3.3.1.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfectomobile\\intellij-connector\\10.3.0.1\\intellij-connector-10.3.0.1.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-testng\\1.1.15\\reportium-testng-1.1.15.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfecto\\reporting-sdk\\reportium-java\\1.1.15\\reportium-java-1.1.15.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfectomobile\\pm-webdriver\\10.3.0.4\\pm-webdriver-10.3.0.4.jar;C:\\Users\\Allen\\.m2\\repository\\com\\perfectomobile\\http-client\\10.3.0.4\\http-client-10.3.0.4.jar;C:\\Users\\Allen\\.m2\\repository\\info\\cukes\\gherkin\\2.12.2\\gherkin-2.12.2.jar;C:\\Users\\Allen\\.m2\\repository\\com\\xframium\\xframium-serialization\\2.0.6\\xframium-serialization-2.0.6.jar;C:\\Users\\Allen\\.m2\\repository\\org\\json\\json\\20160212\\json-20160212.jar;C:\\Users\\Allen\\.m2\\repository\\javax\\mail\\mail\\1.5.0-b01\\mail-1.5.0-b01.jar;C:\\Users\\Allen\\.m2\\repository\\com\\joestelmach\\natty\\0.12\\natty-0.12.jar;C:\\Users\\Allen\\.m2\\repository\\org\\mnode\\ical4j\\ical4j\\1.0.2\\ical4j-1.0.2.jar;C:\\Users\\Allen\\.m2\\repository\\commons-lang\\commons-lang\\2.6\\commons-lang-2.6.jar;C:\\Users\\Allen\\.m2\\repository\\backport-util-concurrent\\backport-util-concurrent\\3.1\\backport-util-concurrent-3.1.jar;C:\\Users\\Allen\\git\\xframium-java\\alm\\target\\classes;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv-platform\\3.2.0-1.3\\opencv-platform-3.2.0-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp\\1.3\\javacpp-1.3.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-android-arm.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-android-x86.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-linux-x86.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-linux-x86_64.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-linux-armhf.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-linux-ppc64le.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-macosx-x86_64.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-windows-x86.jar;C:\\Users\\Allen\\.m2\\repository\\org\\bytedeco\\javacpp-presets\\opencv\\3.2.0-1.3\\opencv-3.2.0-1.3-windows-x86_64.jar;C:\\Users\\Allen\\.m2\\repository\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;C:\\Users\\Allen\\.m2\\repository\\org\\slf4j\\slf4j-jdk14\\1.7.25\\slf4j-jdk14-1.7.25.jar",
        "java.vm.vendor": "Oracle Corporation",
        "sun.arch.data.model": "64",
        "user.variant": "",
        "java.vendor.url": "http://java.oracle.com/",
        "user.timezone": "America/New_York",
        "__userName": "morelandlabs",
        "os.name": "Windows 10",
        "java.vm.specification.version": "1.8",
        "user.country": "US",
        "sun.java.launcher": "SUN_STANDARD",
        "sun.boot.library.path": "C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\bin",
        "sun.java.command": "org.xframium.driver.TestDriver C:\\Users\\Allen\\git\\xframium-java\\testing\\driverConfig.xml",
        "selenium.LOGGER": "c:\\projects\\selenium.log",
        "sun.cpu.endian": "little",
        "user.home": "C:\\Users\\Allen",
        "user.language": "en",
        "java.specification.vendor": "Oracle Corporation",
        "java.home": "C:\\Program Files\\Java\\jdk1.8.0_111\\jre",
        "file.separator": "\\",
        "line.separator": "\r\n",
        "java.vm.specification.vendor": "Oracle Corporation",
        "java.specification.name": "Java Platform API Specification",
        "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
        "__cloudUrl": "https://ondemand.saucelabs.com:80",
        "sun.boot.class.path": "C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\resources.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\rt.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\jsse.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\jce.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\charsets.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\jfr.jar;C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\classes",
        "user.script": "",
        "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
        "java.runtime.version": "1.8.0_111-b14",
        "user.name": "Allen",
        "path.separator": ";",
        "os.version": "10.0",
        "java.endorsed.dirs": "C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\endorsed",
        "java.runtime.name": "Java(TM) SE Runtime Environment",
        "file.encoding": "Cp1252",
        "__password": "3889050d-3b2c-4641-b37f-f8ad4d7c26bb",
        "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
        "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
        "java.io.tmpdir": "C:\\Users\\Allen\\AppData\\Local\\Temp\\",
        "java.version": "1.8.0_111",
        "user.dir": "C:\\Users\\Allen\\git\\xframium-java\\driver",
        "os.arch": "amd64",
        "webdriver.gecko.driver": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\geckodriver-1.0.11.exe",
        "java.vm.specification.name": "Java Virtual Machine Specification",
        "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
        "sun.os.patch.level": "",
        "java.library.path": "C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\bin;C:\\WINDOWS\\Sun\\Java\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\oraclexe\\app\\oracle\\product\\11.2.0\\server\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\nodejs\\;c:\\program files\\java\\jdk1.8.0_71\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\Allen\\AppData\\Roaming\\npm;C:\\Users\\Allen\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Program Files\\Heroku\\bin;.",
        "java.vm.info": "mixed mode",
        "java.vendor": "Oracle Corporation",
        "java.vm.version": "25.111-b14",
        "java.ext.dirs": "C:\\Program Files\\Java\\jdk1.8.0_111\\jre\\lib\\ext;C:\\WINDOWS\\Sun\\Java\\lib\\ext",
        "sun.io.unicode.encoding": "UnicodeLittle",
        "selenium.LOGGER.level": "WARNING",
        "java.class.version": "52.0"
    },
    "testException": "null",
    "stepList": [
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                "kwDescription": "Allows the script to call another pre-defined function or test.  You can pass named context parameters that are scoped to the =function call by adding parameters with names and values.  OVERRIDE is the only reserved name using for overriding data provider names",
                "validationType": "null",
                "kwHelp": "https://www.xframium.org/keyword.html#kw-call",
                "siteName": "xTest",
                "description": "",
                "threshold": "0",
                "poi": "null",
                "sFailure": "ERROR",
                "pageName": "home",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "Call Test/Function",
                "numberGenerator": "java.util.Random@2257437",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": true,
                "kwImpl": "org.xframium.page.keyWord.step.spi.KWSCall2",
                "stepList": [],
                "kw": "CALL2",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "kw-set",
                "parameterList": [],
                "category": "Flow Control",
                "orMapping": false,
                "waitTime": "0",
                "device": "null"
            },
            "startTime": {
                "dateTime": "05/26/2017-11:09:54",
                "dateOnly": "05/26/2017",
                "timeOnly": "11:09:54",
                "raw": 1495811394542
            },
            "endTime": {
                "dateTime": "05/26/2017-11:12:06",
                "dateOnly": "05/26/2017",
                "timeOnly": "11:12:06",
                "raw": 1495811526546
            },
            "stepList": [
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["SET_VALUE"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "focusId",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "SET_VALUE"
                        }],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:09:54",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:09:54",
                        "raw": 1495811394577
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:09:57",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:09:57",
                        "raw": 1495811397719
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "SET_VALUE",
                        "value"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Extracting an attribute value from <span class=\"elementName\">%s<\/span> element on the page <span class=\"pageName\">%s<\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to interact with individual attributes of the names element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-attribute",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Attribute Interaction",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSAttribute",
                        "stepList": [],
                        "kw": "ATTRIBUTE",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "focusId",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "SET_VALUE"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "value"
                            }
                        ],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:09:57",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:09:57",
                        "raw": 1495811397719
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:09:57",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:09:57",
                        "raw": 1495811397934
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "NEW SET_VALUE",
                        "DELAYED"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "focusId",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "NEW SET_VALUE"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "DELAYED"
                            }
                        ],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:09:57",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:09:57",
                        "raw": 1495811397934
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:42",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:42",
                        "raw": 1495811502358
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "NEW SET_VALUE",
                        "value"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Extracting an attribute value from <span class=\"elementName\">%s<\/span> element on the page <span class=\"pageName\">%s<\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to interact with individual attributes of the names element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-attribute",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Attribute Interaction",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSAttribute",
                        "stepList": [],
                        "kw": "ATTRIBUTE",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "focusId",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "NEW SET_VALUE"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "value"
                            }
                        ],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:42",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:42",
                        "raw": 1495811502358
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:42",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:42",
                        "raw": 1495811502731
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "xxx",
                        "SINGLE"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "focusId",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "xxx"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "SINGLE"
                            }
                        ],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:42",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:42",
                        "raw": 1495811502731
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:43",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:43",
                        "raw": 1495811503365
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "NEW SET_VALUExxx",
                        "value"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Extracting an attribute value from <span class=\"elementName\">%s<\/span> element on the page <span class=\"pageName\">%s<\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to interact with individual attributes of the names element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-attribute",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Attribute Interaction",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSAttribute",
                        "stepList": [],
                        "kw": "ATTRIBUTE",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "focusId",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "NEW SET_VALUExxx"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "value"
                            }
                        ],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:43",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:43",
                        "raw": 1495811503365
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:43",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:43",
                        "raw": 1495811503555
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["2"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "2"
                        }],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:43",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:43",
                        "raw": 1495811503555
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:52",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:52",
                        "raw": 1495811512248
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["Two"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Retrieved the value of the <span class=\"elementName\">%s<\/span> element on the page<span class=\"pageName\">%s<\/span> as <span class=\"pass\"><b>%s<\/b><\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to extract a value for an element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-get",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Get Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSValue",
                        "stepList": [],
                        "kw": "GET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "Two"
                        }],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:52",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:52",
                        "raw": 1495811512248
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:53",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:53",
                        "raw": 1495811513804
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["Three"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "Three"
                        }],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:53",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:53",
                        "raw": 1495811513804
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:54",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:54",
                        "raw": 1495811514970
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["Three"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Retrieved the value of the <span class=\"elementName\">%s<\/span> element on the page<span class=\"pageName\">%s<\/span> as <span class=\"pass\"><b>%s<\/b><\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to extract a value for an element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-get",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Get Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSValue",
                        "stepList": [],
                        "kw": "GET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "Three"
                        }],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:54",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:54",
                        "raw": 1495811514970
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:56",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:56",
                        "raw": 1495811516641
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "2",
                        "BY_VALUE"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "2"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "BY_VALUE"
                            }
                        ],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:56",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:56",
                        "raw": 1495811516641
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:58",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:58",
                        "raw": 1495811518035
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["Two"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Retrieved the value of the <span class=\"elementName\">%s<\/span> element on the page<span class=\"pageName\">%s<\/span> as <span class=\"pass\"><b>%s<\/b><\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to extract a value for an element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-get",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Get Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSValue",
                        "stepList": [],
                        "kw": "GET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "Two"
                        }],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:58",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:58",
                        "raw": 1495811518035
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:11:59",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:59",
                        "raw": 1495811519670
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": [
                        "Three",
                        "BY_VISIBLE_TEXT"
                    ],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "Three"
                            },
                            {
                                "fileName": "null",
                                "usage": "null",
                                "name": "null",
                                "type": "STATIC",
                                "tokenList": [],
                                "value": "BY_VISIBLE_TEXT"
                            }
                        ],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:11:59",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:11:59",
                        "raw": 1495811519670
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:12:01",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:01",
                        "raw": 1495811521076
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["Three"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Retrieved the value of the <span class=\"elementName\">%s<\/span> element on the page<span class=\"pageName\">%s<\/span> as <span class=\"pass\"><b>%s<\/b><\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to extract a value for an element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-get",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Get Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSValue",
                        "stepList": [],
                        "kw": "GET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "selectBox",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "Three"
                        }],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:12:01",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:01",
                        "raw": 1495811521076
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:12:03",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:03",
                        "raw": 1495811523909
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {
                        "SCREENSHOT": "../../artifacts/state4966578505347226172.png",
                        "XML": "../../artifacts/dom-7544730613841623114.xml",
                        "SCREENSHOT_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\artifacts\\state4966578505347226172.png",
                        "HTML": "../../artifacts/dom-7544730613841623114.html",
                        "XML_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\artifacts\\dom-7544730613841623114.xml",
                        "HTML_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\artifacts\\dom-7544730613841623114.html"
                    },
                    "parameterList": [],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "The state of the device has been extracted as <span class=\"elementName\">%s<\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to get a platform checkpoint containing a snapshot image and platform state",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-state",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Platform Checkpoint",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSDumpState",
                        "stepList": [],
                        "kw": "STATE",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "dumpState",
                        "parameterList": [],
                        "category": "Utility",
                        "orMapping": false,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:12:03",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:03",
                        "raw": 1495811523909
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:12:04",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:04",
                        "raw": 1495811524484
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["Bootstrap Four"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "null",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to type or select a value",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-set",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Set Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSSet",
                        "stepList": [],
                        "kw": "SET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "bsSelectUL",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "Bootstrap Four"
                        }],
                        "category": "Interaction",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:12:04",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:04",
                        "raw": 1495811524484
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:12:05",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:05",
                        "raw": 1495811525779
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                },
                {
                    "throwable": "null",
                    "executionParameter": {},
                    "parameterList": ["bsFour"],
                    "step": {
                        "deviceTags": "null",
                        "natualLanguage": "Retrieved the value of the <span class=\"elementName\">%s<\/span> element on the page<span class=\"pageName\">%s<\/span> as <span class=\"pass\"><b>%s<\/b><\/span>",
                        "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                        "kwDescription": "Allows the script to extract a value for an element",
                        "validationType": "null",
                        "kwHelp": "https://www.xframium.org/keyword.html#kw-get",
                        "siteName": "xTest",
                        "description": "",
                        "threshold": "0",
                        "poi": "null",
                        "sFailure": "ERROR",
                        "pageName": "home",
                        "tagNames": "null",
                        "numberFormat": "java.text.DecimalFormat@674dc",
                        "browser": "null",
                        "context": "null",
                        "tokenList": [],
                        "startAt": false,
                        "validation": "null",
                        "kwName": "Get Value",
                        "numberGenerator": "java.util.Random@2257437",
                        "inverse": false,
                        "timed": false,
                        "os": "null",
                        "active": true,
                        "kwImpl": "org.xframium.page.keyWord.step.spi.KWSValue",
                        "stepList": [],
                        "kw": "GET",
                        "version": "null",
                        "breakpoint": false,
                        "fork": false,
                        "linkId": "null",
                        "name": "bsSelectValue",
                        "parameterList": [{
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "bsFour"
                        }],
                        "category": "Verification",
                        "orMapping": true,
                        "waitTime": "0",
                        "device": "null"
                    },
                    "startTime": {
                        "dateTime": "05/26/2017-11:12:05",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:05",
                        "raw": 1495811525779
                    },
                    "endTime": {
                        "dateTime": "05/26/2017-11:12:06",
                        "dateOnly": "05/26/2017",
                        "timeOnly": "11:12:06",
                        "raw": 1495811526546
                    },
                    "stepList": [],
                    "message": "null",
                    "timingMap": {},
                    "stepStatus": "SUCCESS"
                }
            ],
            "message": "null",
            "timingMap": {},
            "stepStatus": "SUCCESS"
        },
        {
            "throwable": "null",
            "executionParameter": {},
            "parameterList": [],
            "step": {
                "deviceTags": "null",
                "natualLanguage": "null",
                "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                "kwDescription": "null",
                "validationType": "null",
                "kwHelp": "null",
                "siteName": "null",
                "description": "null",
                "threshold": "0",
                "poi": "null",
                "sFailure": "null",
                "pageName": "null",
                "tagNames": "null",
                "numberFormat": "java.text.DecimalFormat@674dc",
                "browser": "null",
                "context": "null",
                "tokenList": [],
                "startAt": false,
                "validation": "null",
                "kwName": "N/A",
                "numberGenerator": "java.util.Random@2257437",
                "inverse": false,
                "timed": false,
                "os": "null",
                "active": false,
                "kwImpl": "org.xframium.page.keyWord.step.SyntheticStep",
                "stepList": [],
                "kw": "CALL2",
                "version": "null",
                "breakpoint": false,
                "fork": false,
                "linkId": "null",
                "name": "Report Test Success",
                "parameterList": [],
                "category": "Other",
                "orMapping": true,
                "waitTime": "0",
                "device": "null"
            },
            "startTime": {
                "dateTime": "05/26/2017-11:12:06",
                "dateOnly": "05/26/2017",
                "timeOnly": "11:12:06",
                "raw": 1495811526546
            },
            "endTime": {
                "dateTime": "05/26/2017-11:12:06",
                "dateOnly": "05/26/2017",
                "timeOnly": "11:12:06",
                "raw": 1495811526577
            },
            "stepList": [{
                "throwable": "null",
                "executionParameter": {"REPORT_ENTRY": "reportSuccess\tTEST STATUS:\tPASSED\t"},
                "parameterList": [
                    "TEST STATUS:",
                    "PASSED"
                ],
                "step": {
                    "deviceTags": "null",
                    "natualLanguage": "null",
                    "log": "org.apache.commons.logging.impl.Jdk14Logger@1068478e",
                    "kwDescription": "Allows the script to add a parameter value to the output report or CSV file",
                    "validationType": "null",
                    "kwHelp": "https://www.xframium.org/keyword.html#kw-report",
                    "siteName": "xTest",
                    "description": "",
                    "threshold": "0",
                    "poi": "null",
                    "sFailure": "ERROR",
                    "pageName": "home",
                    "tagNames": "null",
                    "numberFormat": "java.text.DecimalFormat@674dc",
                    "browser": "null",
                    "context": "null",
                    "tokenList": [],
                    "startAt": false,
                    "validation": "null",
                    "kwName": "Report Item",
                    "numberGenerator": "java.util.Random@2257437",
                    "inverse": false,
                    "timed": false,
                    "os": "null",
                    "active": true,
                    "kwImpl": "org.xframium.page.keyWord.step.spi.KWSReport",
                    "stepList": [],
                    "kw": "REPORT",
                    "version": "null",
                    "breakpoint": false,
                    "fork": false,
                    "linkId": "null",
                    "name": "reportSuccess",
                    "parameterList": [
                        {
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "STATIC",
                            "tokenList": [],
                            "value": "TEST STATUS:"
                        },
                        {
                            "fileName": "null",
                            "usage": "null",
                            "name": "null",
                            "type": "CONTEXT",
                            "tokenList": [],
                            "value": "XF_TEST_STATUS"
                        }
                    ],
                    "category": "Utility",
                    "orMapping": false,
                    "waitTime": "0",
                    "device": "null"
                },
                "startTime": {
                    "dateTime": "05/26/2017-11:12:06",
                    "dateOnly": "05/26/2017",
                    "timeOnly": "11:12:06",
                    "raw": 1495811526546
                },
                "endTime": {
                    "dateTime": "05/26/2017-11:12:06",
                    "dateOnly": "05/26/2017",
                    "timeOnly": "11:12:06",
                    "raw": 1495811526577
                },
                "stepList": [],
                "message": "null",
                "timingMap": {},
                "stepStatus": "SUCCESS"
            }],
            "message": "null",
            "timingMap": {},
            "stepStatus": "SUCCESS"
        }
    ],
    "sessionId": "alleng@perfectomobile.com_RemoteWebDriver_17-05-26_15_09_40_6165",
    "message": "null",
    "callMap": {},
    "currentStep": "null",
    "endTime": {
        "dateTime": "05/26/2017-11:12:06",
        "dateOnly": "05/26/2017",
        "timeOnly": "11:12:06",
        "raw": 1495811526577
    },
    "folderName": "iPhone iOS\\SET Test",
    "cloudDescriptor": {
        "hostName": "allstate.perfectomobile.com",
        "proxyPort": "null",
        "password": "Perfecto123",
        "deviceAction": "null",
        "provider": "PERFECTO",
        "gridInstance": "null",
        "name": "perfecto",
        "description": "",
        "userName": "alleng@perfectomobile.com",
        "proxyHost": "null",
        "gesture": "null"
    },
    "contextMap": {
        "_SCREENSHOT": "../../artifacts/state4966578505347226172.png",
        "_DOM_XML_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\artifacts\\dom-7544730613841623114.xml",
        "_SCREENSHOT_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\artifacts\\state4966578505347226172.png",
        "_DOM_XML": "../../artifacts/dom-7544730613841623114.xml",
        "_DOM_HTML": "../../artifacts/dom-7544730613841623114.html",
        "_DOM_HTML_ABS": "C:\\Users\\Allen\\git\\xframium-java\\testing\\test-output\\05-26_11-09-52-541\\artifacts\\dom-7544730613841623114.html",
        "XF_TEST_STATUS": "PASSED"
    },
    "device": {
        "capabilities": {},
        "os": "iOS",
        "active": false,
        "deviceLock": "java.util.concurrent.Semaphore@76555cd1[Permits = 1]",
        "deviceName": "97E13ECDB896B4FC689B8AE21D5F97E3E44A5955",
        "resolution": "750x1334",
        "capList": [],
        "driverType": "WEB",
        "tagNames": [],
        "manufacturer": "Apple",
        "cloud": "perfecto",
        "environment": "iPhone-7 iOS 10.2.1",
        "osVersion": "10.2.1",
        "browserVersion": "null",
        "availableDevices": "1",
        "browserName": "null",
        "model": "iPhone-7",
        "cachedString": "null",
        "key": "iPhone iOS"
    },
    "messageDetail": "null"
}};