//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:03:54 PM EDT 
//


package org.xframium.history;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestSuite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestSuite"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="environment" type="{http://www.xframium.org/tcHistory}Environment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="testCase" type="{http://www.xframium.org/tcHistory}TestCase" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="startTime" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="endTime" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="pass" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="fail" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="env" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="os" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="scriptFailure" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="applicationFailure" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="cloudFailure" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *       &lt;attribute name="configFailure" type="{http://www.w3.org/2001/XMLSchema}int" default="0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestSuite", propOrder = {
    "environment",
    "testCase"
})
public class TestSuite {

    protected List<Environment> environment;
    protected List<TestCase> testCase;
    @XmlAttribute(name = "startTime", required = true)
    protected long startTime;
    @XmlAttribute(name = "endTime", required = true)
    protected long endTime;
    @XmlAttribute(name = "fileName", required = true)
    protected String fileName;
    @XmlAttribute(name = "pass", required = true)
    protected int pass;
    @XmlAttribute(name = "fail", required = true)
    protected int fail;
    @XmlAttribute(name = "env", required = true)
    protected int env;
    @XmlAttribute(name = "os", required = true)
    protected int os;
    @XmlAttribute(name = "scriptFailure")
    protected Integer scriptFailure;
    @XmlAttribute(name = "applicationFailure")
    protected Integer applicationFailure;
    @XmlAttribute(name = "cloudFailure")
    protected Integer cloudFailure;
    @XmlAttribute(name = "configFailure")
    protected Integer configFailure;

    /**
     * Gets the value of the environment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the environment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnvironment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Environment }
     * 
     * 
     */
    public List<Environment> getEnvironment() {
        if (environment == null) {
            environment = new ArrayList<Environment>();
        }
        return this.environment;
    }

    /**
     * Gets the value of the testCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestCase }
     * 
     * 
     */
    public List<TestCase> getTestCase() {
        if (testCase == null) {
            testCase = new ArrayList<TestCase>();
        }
        return this.testCase;
    }

    /**
     * Gets the value of the startTime property.
     * 
     */
    public long getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     */
    public void setStartTime(long value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     */
    public long getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     */
    public void setEndTime(long value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the pass property.
     * 
     */
    public int getPass() {
        return pass;
    }

    /**
     * Sets the value of the pass property.
     * 
     */
    public void setPass(int value) {
        this.pass = value;
    }

    /**
     * Gets the value of the fail property.
     * 
     */
    public int getFail() {
        return fail;
    }

    /**
     * Sets the value of the fail property.
     * 
     */
    public void setFail(int value) {
        this.fail = value;
    }

    /**
     * Gets the value of the env property.
     * 
     */
    public int getEnv() {
        return env;
    }

    /**
     * Sets the value of the env property.
     * 
     */
    public void setEnv(int value) {
        this.env = value;
    }

    /**
     * Gets the value of the os property.
     * 
     */
    public int getOs() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     */
    public void setOs(int value) {
        this.os = value;
    }

    /**
     * Gets the value of the scriptFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getScriptFailure() {
        if (scriptFailure == null) {
            return  0;
        } else {
            return scriptFailure;
        }
    }

    /**
     * Sets the value of the scriptFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScriptFailure(Integer value) {
        this.scriptFailure = value;
    }

    /**
     * Gets the value of the applicationFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getApplicationFailure() {
        if (applicationFailure == null) {
            return  0;
        } else {
            return applicationFailure;
        }
    }

    /**
     * Sets the value of the applicationFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setApplicationFailure(Integer value) {
        this.applicationFailure = value;
    }

    /**
     * Gets the value of the cloudFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCloudFailure() {
        if (cloudFailure == null) {
            return  0;
        } else {
            return cloudFailure;
        }
    }

    /**
     * Sets the value of the cloudFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCloudFailure(Integer value) {
        this.cloudFailure = value;
    }

    /**
     * Gets the value of the configFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getConfigFailure() {
        if (configFailure == null) {
            return  0;
        } else {
            return configFailure;
        }
    }

    /**
     * Sets the value of the configFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConfigFailure(Integer value) {
        this.configFailure = value;
    }

}
