//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.08 at 01:49:02 PM EDT 
//


package org.xframium.driver.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xframium.driver.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XFramium_QNAME = new QName("http://www.xframium.org/xFramiumDriver", "xFramium");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xframium.driver.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XFramiumRoot }
     * 
     */
    public XFramiumRoot createXFramiumRoot() {
        return new XFramiumRoot();
    }

    /**
     * Create an instance of {@link XDescription }
     * 
     */
    public XDescription createXDescription() {
        return new XDescription();
    }

    /**
     * Create an instance of {@link XValidator }
     * 
     */
    public XValidator createXValidator() {
        return new XValidator();
    }

    /**
     * Create an instance of {@link XPackage }
     * 
     */
    public XPackage createXPackage() {
        return new XPackage();
    }

    /**
     * Create an instance of {@link XCapabilities }
     * 
     */
    public XCapabilities createXCapabilities() {
        return new XCapabilities();
    }

    /**
     * Create an instance of {@link XObjectDeviceCapability }
     * 
     */
    public XObjectDeviceCapability createXObjectDeviceCapability() {
        return new XObjectDeviceCapability();
    }

    /**
     * Create an instance of {@link XReference }
     * 
     */
    public XReference createXReference() {
        return new XReference();
    }

    /**
     * Create an instance of {@link XOptions }
     * 
     */
    public XOptions createXOptions() {
        return new XOptions();
    }

    /**
     * Create an instance of {@link XElement }
     * 
     */
    public XElement createXElement() {
        return new XElement();
    }

    /**
     * Create an instance of {@link XParameter }
     * 
     */
    public XParameter createXParameter() {
        return new XParameter();
    }

    /**
     * Create an instance of {@link XFunction }
     * 
     */
    public XFunction createXFunction() {
        return new XFunction();
    }

    /**
     * Create an instance of {@link XLibrary }
     * 
     */
    public XLibrary createXLibrary() {
        return new XLibrary();
    }

    /**
     * Create an instance of {@link XInitiator }
     * 
     */
    public XInitiator createXInitiator() {
        return new XInitiator();
    }

    /**
     * Create an instance of {@link XProperty }
     * 
     */
    public XProperty createXProperty() {
        return new XProperty();
    }

    /**
     * Create an instance of {@link XDeviceCapability }
     * 
     */
    public XDeviceCapability createXDeviceCapability() {
        return new XDeviceCapability();
    }

    /**
     * Create an instance of {@link XDevice }
     * 
     */
    public XDevice createXDevice() {
        return new XDevice();
    }

    /**
     * Create an instance of {@link XDependency }
     * 
     */
    public XDependency createXDependency() {
        return new XDependency();
    }

    /**
     * Create an instance of {@link XSecurity }
     * 
     */
    public XSecurity createXSecurity() {
        return new XSecurity();
    }

    /**
     * Create an instance of {@link XArtifact }
     * 
     */
    public XArtifact createXArtifact() {
        return new XArtifact();
    }

    /**
     * Create an instance of {@link XContent }
     * 
     */
    public XContent createXContent() {
        return new XContent();
    }

    /**
     * Create an instance of {@link XActivity }
     * 
     */
    public XActivity createXActivity() {
        return new XActivity();
    }

    /**
     * Create an instance of {@link XPropertyAdapter }
     * 
     */
    public XPropertyAdapter createXPropertyAdapter() {
        return new XPropertyAdapter();
    }

    /**
     * Create an instance of {@link XStep }
     * 
     */
    public XStep createXStep() {
        return new XStep();
    }

    /**
     * Create an instance of {@link XPage }
     * 
     */
    public XPage createXPage() {
        return new XPage();
    }

    /**
     * Create an instance of {@link XModel }
     * 
     */
    public XModel createXModel() {
        return new XModel();
    }

    /**
     * Create an instance of {@link XTest }
     * 
     */
    public XTest createXTest() {
        return new XTest();
    }

    /**
     * Create an instance of {@link XPackages }
     * 
     */
    public XPackages createXPackages() {
        return new XPackages();
    }

    /**
     * Create an instance of {@link XApplication }
     * 
     */
    public XApplication createXApplication() {
        return new XApplication();
    }

    /**
     * Create an instance of {@link XDriver }
     * 
     */
    public XDriver createXDriver() {
        return new XDriver();
    }

    /**
     * Create an instance of {@link XSuite }
     * 
     */
    public XSuite createXSuite() {
        return new XSuite();
    }

    /**
     * Create an instance of {@link XReferences }
     * 
     */
    public XReferences createXReferences() {
        return new XReferences();
    }

    /**
     * Create an instance of {@link XSimpleElement }
     * 
     */
    public XSimpleElement createXSimpleElement() {
        return new XSimpleElement();
    }

    /**
     * Create an instance of {@link XProxy }
     * 
     */
    public XProxy createXProxy() {
        return new XProxy();
    }

    /**
     * Create an instance of {@link XTag }
     * 
     */
    public XTag createXTag() {
        return new XTag();
    }

    /**
     * Create an instance of {@link XCloud }
     * 
     */
    public XCloud createXCloud() {
        return new XCloud();
    }

    /**
     * Create an instance of {@link XToken }
     * 
     */
    public XToken createXToken() {
        return new XToken();
    }

    /**
     * Create an instance of {@link XData }
     * 
     */
    public XData createXData() {
        return new XData();
    }

    /**
     * Create an instance of {@link XElementParameter }
     * 
     */
    public XElementParameter createXElementParameter() {
        return new XElementParameter();
    }

    /**
     * Create an instance of {@link XFlow }
     * 
     */
    public XFlow createXFlow() {
        return new XFlow();
    }

    /**
     * Create an instance of {@link XDevices }
     * 
     */
    public XDevices createXDevices() {
        return new XDevices();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XFramiumRoot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xframium.org/xFramiumDriver", name = "xFramium")
    public JAXBElement<XFramiumRoot> createXFramium(XFramiumRoot value) {
        return new JAXBElement<XFramiumRoot>(_XFramium_QNAME, XFramiumRoot.class, null, value);
    }

}
