//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.10 at 10:00:26 AM EDT 
//


package org.xframium.driver.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines an Artifact that is to be produced during test execution
 * 
 * <p>Java class for xArtifact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xArtifact"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="EXECUTION_REPORT_PDF"/&gt;
 *             &lt;enumeration value="EXECUTION_REPORT_HTML"/&gt;
 *             &lt;enumeration value="EXECUTION_REPORT_XML"/&gt;
 *             &lt;enumeration value="EXECUTION_REPORT_CSV"/&gt;
 *             &lt;enumeration value="FAILURE_SOURCE"/&gt;
 *             &lt;enumeration value="FAILURE_SOURCE_HTML"/&gt;
 *             &lt;enumeration value="IMAGING_ANALYSIS"/&gt;
 *             &lt;enumeration value="DEVICE_LOG"/&gt;
 *             &lt;enumeration value="CONSOLE_LOG"/&gt;
 *             &lt;enumeration value="EXECUTION_RECORD_HTML"/&gt;
 *             &lt;enumeration value="EXECUTION_RECORD_CSV"/&gt;
 *             &lt;enumeration value="EXECUTION_RECORD"/&gt;
 *             &lt;enumeration value="EXECUTION_TIMING"/&gt;
 *             &lt;enumeration value="EXECUTION_DEFINITION"/&gt;
 *             &lt;enumeration value="DEBUGGER"/&gt;
 *             &lt;enumeration value="SAUCE_LABS"/&gt;
 *             &lt;enumeration value="REPORTIUM"/&gt;
 *             &lt;enumeration value="EXECUTION_RECORD_JSON"/&gt;
 *             &lt;enumeration value="GRID_REPORT"/&gt;
 *             &lt;enumeration value="GRID_HTML"/&gt;
 *             &lt;enumeration value="ADD_TO_CSV"/&gt;
 *             &lt;enumeration value="ALM_DEFECT"/&gt;
 *             &lt;enumeration value="EXECUTION_SUITE_JSON"/&gt;
 *             &lt;enumeration value="EXECUTION_SUITE_HTML"/&gt;
 *             &lt;enumeration value="EXECUTION_HISTORY_JSON"/&gt;
 *             &lt;enumeration value="EXECUTION_HISTORY_HTML"/&gt;
 *             &lt;enumeration value="WIND_TUNNEL"/&gt;
 *             &lt;enumeration value="EXECUTION_TEST_JSON"/&gt;
 *             &lt;enumeration value="EXECUTION_TEST_HTML"/&gt;
 *             &lt;enumeration value="TIMING_HTML"/&gt;
 *             &lt;enumeration value="STATISTICS"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xArtifact")
public class XArtifact {

    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "active")
    protected Boolean active;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isActive() {
        if (active == null) {
            return true;
        } else {
            return active;
        }
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

}
