insert into PERFECTO_TEST_SUITES ( NAME )
values( '' );

insert into PERFECTO_TEST_SUITE_PAGES ( NAME, PAGE_NAME, CLASS_NAME )
values( '', '', NULL );

insert into PERFECTO_TEST_IMPORTED_SUITES ( SUITE_NAME, IMPORTED_NAME, INCLUDE_TESTS, INCLUDE_FUNCTIONS )
values ( '', '', NULL, NULL );

insert into PERFECTO_TESTS ( SUITE_NAME, NAME, DATA_DRIVER, DATA_PROVIDER, LINK_ID, TIMED, THRESHOLD, ACTIVE, OS, TAG_NAMES )
values( '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );

insert into PERFECTO_TEST_STEPS ( KEY, SUITE_NAME, TEST_NAME, NAME, PAGE_NAME, TYPE, ACTIVE, LINK_ID, OS,
                                 POI, THRESHOLD, TIMED, INVERSE, WAIT, FAILURE_MODE, VALIDATION, VALIDATION_TYPE,
                                 DEVICE, TAG_NAMES, OFFSET )
values ( '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1 );

insert into PERFECTO_TEST_SUBSTEPS( PARENT_KEY, CHILD_KEY )
values ( '', '' );

insert into PERFECTO_TEST_STEP_PARAMS ( STEP_KEY, TYPE, VALUE, OFFSET )
values ( '', NULL, '', 1 );

insert into PERFECTO_TEST_STEP_TOKENS ( STEP_KEY, NAME, TYPE, VALUE )
values ( '', '', '', NULL );

insert into PERFECTO_FUNCTIONS ( SUITE_NAME, NAME, DATA_DRIVER, DATA_PROVIDER, LINK_ID, TIMED, THRESHOLD, ACTIVE, OS )
values( '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL );
