//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.26 at 07:48:06 AM EDT 
//


package org.xframium.device.cloud.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeepAlive complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KeepAlive">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pollTime" type="{http://www.w3.org/2001/XMLSchema}int" default="10" />
 *       &lt;attribute name="quietTime" type="{http://www.w3.org/2001/XMLSchema}int" default="60" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KeepAlive")
public class KeepAlive {

    @XmlAttribute(name = "implementation", required = true)
    protected String implementation;
    @XmlAttribute(name = "pollTime")
    protected Integer pollTime;
    @XmlAttribute(name = "quietTime")
    protected Integer quietTime;

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the pollTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPollTime() {
        if (pollTime == null) {
            return  10;
        } else {
            return pollTime;
        }
    }

    /**
     * Sets the value of the pollTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPollTime(Integer value) {
        this.pollTime = value;
    }

    /**
     * Gets the value of the quietTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getQuietTime() {
        if (quietTime == null) {
            return  60;
        } else {
            return quietTime;
        }
    }

    /**
     * Sets the value of the quietTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuietTime(Integer value) {
        this.quietTime = value;
    }

}
